### ISSUE TITLE
Order package

### ISSUE THREAD

**Issue by scrock1987** [plannifnminus1fails/destiny#100]
## Tasks:
- [x] Place order from cart will initaiate the order.
   * - [ ] Create a new Module/package for order.
   * - [ ] Create a model for Order.
   * - [ ] Create services for saving and retrieving Order from DB.

- [x] Order management page in user menu
  *  - [ ] Lists all the orders for a user/ Admin gets all the orders

**Comment by plannifnminus1fails** [comment]
1. Create node routes
 - Create order
 - Fetch an order
 - Fetch all orders for current user

2. Create Angular route
 - All orders for current user
 - Order detail

3. Send emails to user & admin to notify order detail

4.  Refer Order object sample: Add/remove fields where necessary 

{
  "shipping": 2.99,
  "tax": 10.13,
  "taxRate": 7.5,
  "subTotal": 135,
  "totalCost": 148.12,
  "items": [
    {
      "id": "5490266282b4cdfa6a89277c",
      "name": "fasdfasdf",
      "price": 100,
      "quantity": 1,
      "data": {
        "__v": 0,
        "_id": "5490266282b4cdfa6a89277c",
        "category": {
          "_id": "54634e05a92d436556ae189a",
          "name": "Accessories"
        },
        "color": "asfda",
        "description": "DVD",
        "price": "100",
        "tag": "afsdf",
        "title": "fasdfasdf",
        "user": {
          "_id": "541c311b47740f0919fb8cf8",
          "name": "Amit kumar",
          "username": "plann"
        },
        "images": {
          "name": "bb.png",
          "src": "/files/public/photos/bb.png",
          "size": "119098",
          "type": "image/png",
          "created": "2014-12-23T12:12:38.644Z"
        },
        "created": "2014-12-16T12:32:34.142Z"
      },
      "total": 100
    },
    {
      "id": "5490267782b4cdfa6a89277d",
      "name": "Thinkpad",
      "price": 35,
      "quantity": 1,
      "data": {
        "__v": 0,
        "_id": "5490267782b4cdfa6a89277d",
        "category": {
          "_id": "54634e05a92d436556ae189a",
          "name": "Accessories"
        },
        "color": "asfdsdf",
        "description": "Laptop",
        "price": "35K",
        "tag": "sdafas",
        "title": "Thinkpad",
        "user": {
          "_id": "541c311b47740f0919fb8cf8",
          "name": "Amit kumar",
          "username": "plann"
        },
        "images": {
          "name": "lenovo-laptop-thinkpad-edge-e431-front.png",
          "src": "/files/public/photos/lenovo-laptop-thinkpad-edge-e431-front.png",
          "size": "82255",
          "type": "image/png",
          "created": "2014-12-23T12:12:13.533Z"
        },
        "created": "2014-12-16T12:32:55.020Z"
      },
      "total": 35
    }
  ],
  "user": "541c311b47740f0919fb8cf8"
}
