### ISSUE TITLE
Cart should be stored in database

### ISSUE THREAD

**Issue by scrock1987** [plannifnminus1fails/destiny#99]
- [ ] Create cart dynamically i.e. it does not loose its contents when refreshed.
  * - [ ] Create a collection for cart per user session.
Update existing cart functionality to achive this.

**Comment by plannifnminus1fails** [comment]
### Tasks ###
- [ ] Prepare cart object by appending userid to response of ngCart.toObject()

Sample object:
{
  "shipping": 2.99,
  "tax": 10.13,
  "taxRate": 7.5,
  "subTotal": 135,
  "totalCost": 148.12,
  "items": [
    {
      "id": "5490266282b4cdfa6a89277c",
      "name": "fasdfasdf",
      "price": 100,
      "quantity": 1,
      "data": {
        "__v": 0,
        "_id": "5490266282b4cdfa6a89277c",
        "category": {
          "_id": "54634e05a92d436556ae189a",
          "name": "Accessories"
        },
        "color": "asfda",
        "description": "DVD",
        "price": "100",
        "tag": "afsdf",
        "title": "fasdfasdf",
        "user": {
          "_id": "541c311b47740f0919fb8cf8",
          "name": "Amit kumar",
          "username": "plann"
        },
        "images": {
          "name": "bb.png",
          "src": "/files/public/photos/bb.png",
          "size": "119098",
          "type": "image/png",
          "created": "2014-12-23T12:12:38.644Z"
        },
        "created": "2014-12-16T12:32:34.142Z"
      },
      "total": 100
    },
    {
      "id": "5490267782b4cdfa6a89277d",
      "name": "Thinkpad",
      "price": 35,
      "quantity": 1,
      "data": {
        "__v": 0,
        "_id": "5490267782b4cdfa6a89277d",
        "category": {
          "_id": "54634e05a92d436556ae189a",
          "name": "Accessories"
        },
        "color": "asfdsdf",
        "description": "Laptop",
        "price": "35K",
        "tag": "sdafas",
        "title": "Thinkpad",
        "user": {
          "_id": "541c311b47740f0919fb8cf8",
          "name": "Amit kumar",
          "username": "plann"
        },
        "images": {
          "name": "lenovo-laptop-thinkpad-edge-e431-front.png",
          "src": "/files/public/photos/lenovo-laptop-thinkpad-edge-e431-front.png",
          "size": "82255",
          "type": "image/png",
          "created": "2014-12-23T12:12:13.533Z"
        },
        "created": "2014-12-16T12:32:55.020Z"
      },
      "total": 35
    }
  ],
  "user": "541c311b47740f0919fb8cf8"
}

**Comment by plannifnminus1fails** [comment]
Cart object sample:

{
  "shipping": 2.99,
  "tax": 10.13,
  "taxRate": 7.5,
  "subTotal": 135,
  "totalCost": 148.12,
  "items": [
    {
      "id": "5490266282b4cdfa6a89277c",
      "name": "fasdfasdf",
      "price": 100,
      "quantity": 1,
      "data": {
        "__v": 0,
        "_id": "5490266282b4cdfa6a89277c",
        "category": {
          "_id": "54634e05a92d436556ae189a",
          "name": "Accessories"
        },
        "color": "asfda",
        "description": "DVD",
        "price": "100",
        "tag": "afsdf",
        "title": "fasdfasdf",
        "user": {
          "_id": "541c311b47740f0919fb8cf8",
          "name": "Amit kumar",
          "username": "plann"
        },
        "images": {
          "name": "bb.png",
          "src": "/files/public/photos/bb.png",
          "size": "119098",
          "type": "image/png",
          "created": "2014-12-23T12:12:38.644Z"
        },
        "created": "2014-12-16T12:32:34.142Z"
      },
      "total": 100
    },
    {
      "id": "5490267782b4cdfa6a89277d",
      "name": "Thinkpad",
      "price": 35,
      "quantity": 1,
      "data": {
        "__v": 0,
        "_id": "5490267782b4cdfa6a89277d",
        "category": {
          "_id": "54634e05a92d436556ae189a",
          "name": "Accessories"
        },
        "color": "asfdsdf",
        "description": "Laptop",
        "price": "35K",
        "tag": "sdafas",
        "title": "Thinkpad",
        "user": {
          "_id": "541c311b47740f0919fb8cf8",
          "name": "Amit kumar",
          "username": "plann"
        },
        "images": {
          "name": "lenovo-laptop-thinkpad-edge-e431-front.png",
          "src": "/files/public/photos/lenovo-laptop-thinkpad-edge-e431-front.png",
          "size": "82255",
          "type": "image/png",
          "created": "2014-12-23T12:12:13.533Z"
        },
        "created": "2014-12-16T12:32:55.020Z"
      },
      "total": 35
    }
  ],
  "user": "541c311b47740f0919fb8cf8"
}

**Comment by plannifnminus1fails** [comment]
Actual Cart record:

{
  "_id": ObjectId("54ec195e77b51a8d22cb6d98"),
  "items": [
    {
      "_id": "54d1ee3a8c9e796f0418875c",
      "_name": "ghost logo",
      "_price": NumberInt(4),
      "_quantity": NumberInt(1),
      "_data": {
        "created": "2015-02-04T10:02:34.989Z",
        "images": {
          "created": "2015-02-12T06:52:42.104Z",
          "type": "image\/png",
          "size": "15974",
          "src": "\/files\/public\/photos\/ghost_black.png",
          "name": "ghost_black.png"
        },
        "user": {
          "username": "plann",
          "name": "Amit kumar",
          "_id": "541c311b47740f0919fb8cf8"
        },
        "title": "ghost logo",
        "tag": "4",
        "price": "4",
        "description": "toy product",
        "color": "black",
        "category": {
          "name": "Toys",
          "_id": "54635342fd252e1cfff91d89"
        },
        "_id": "54d1ee3a8c9e796f0418875c",
        "__v": NumberInt(0)
      }
    },
    {
      "_id": "5490267782b4cdfa6a89277d",
      "_name": "Thinkpad",
      "_price": NumberInt(35),
      "_quantity": NumberInt(4),
      "_data": {
        "created": "2014-12-16T12:32:55.020Z",
        "images": {
          "created": "2015-02-06T09:40:23.282Z",
          "type": "image\/png",
          "size": "82255",
          "src": "\/files\/public\/photos\/lenovo-laptop-thinkpad-edge-e431-front.png",
          "name": "lenovo-laptop-thinkpad-edge-e431-front.png"
        },
        "user": {
          "username": "plann",
          "name": "Amit kumar",
          "_id": "541c311b47740f0919fb8cf8"
        },
        "title": "Thinkpad",
        "tag": "sdafas",
        "price": "35",
        "description": "Laptop",
        "color": "asfdsdf",
        "category": {
          "name": "Accessories",
          "_id": "54634e05a92d436556ae189a"
        },
        "_id": "5490267782b4cdfa6a89277d",
        "__v": NumberInt(0)
      }
    },
    {
      "_id": "54af94f3671493813594251a",
      "_name": "nexus 7",
      "_price": NumberInt(20000),
      "_quantity": NumberInt(1),
      "_data": {
        "created": "2015-01-09T08:44:35.549Z",
        "images": {
          "created": "2015-01-09T08:41:00.359Z",
          "type": "image\/gif",
          "size": "8149",
          "src": "\/files\/public\/photos\/go.gif",
          "name": "go.gif"
        },
        "__v": NumberInt(0),
        "_id": "54af94f3671493813594251a",
        "category": {
          "name": "Toys",
          "_id": "54635342fd252e1cfff91d89"
        },
        "price": "20000",
        "color": "black",
        "tag": "nexus",
        "description": "phone",
        "title": "nexus 7",
        "user": {
          "username": "plann",
          "name": "Amit kumar",
          "_id": "541c311b47740f0919fb8cf8"
        }
      }
    },
    {
      "_id": "54af94d16714938135942519",
      "_name": "nexus 6",
      "_price": NumberInt(20000),
      "_quantity": NumberInt(4),
      "_data": {
        "created": "2015-01-09T08:44:01.727Z",
        "images": {
          "created": "2015-01-09T08:41:00.359Z",
          "type": "image\/gif",
          "size": "8149",
          "src": "\/files\/public\/photos\/go.gif",
          "name": "go.gif"
        },
        "__v": NumberInt(0),
        "_id": "54af94d16714938135942519",
        "category": {
          "name": "Toys",
          "_id": "54635342fd252e1cfff91d89"
        },
        "price": "20000",
        "color": "black",
        "tag": "nexus",
        "description": "phone",
        "title": "nexus 6",
        "user": {
          "username": "plann",
          "name": "Amit kumar",
          "_id": "541c311b47740f0919fb8cf8"
        }
      }
    }
  ],
  "shipping": null,
  "tax": null,
  "taxRate": null,
  "user": "541c311b47740f0919fb8cf8"
}
